@token={{$dotenv token}}

GET https://api.github.com/repos/kwiksher/kwik5-project-template/releases/latest
Authorization: token {{token}}

# Doc
POST https://api.github.com/repos/kwiksher/kwik-visual-code/actions/workflows/gh-pages.yaml/dispatches
Authorization: token {{token}}
Accept: application/vnd.github+json
Content-Type: application/json
{
  "ref": "develop"
}

# 1 UXP kwik-exporter build main.js
POST https://api.github.com/repos/kwiksher/kwik-visual-code/actions/workflows/kwik-exporter.yaml/dispatches
Authorization: token {{token}}
Accept: application/vnd.github+json
Content-Type: application/json
{
  "ref": "develop"
}

# 2 kwik5-plugin's kwik/**/+.lua to UXP's base-proj
POST https://api.github.com/repos/kwiksher/kwik5-plugin/actions/workflows/kwik-base-proj.yaml/dispatches
Authorization: token {{token}}
Accept: application/vnd.github+json
Content-Type: application/json
{
  "ref": "develop"
}

# 3 kwik5-sample-book, App/book to UXP's base-proj
POST https://api.github.com/repos/kwiksher/kwik5-sample-books/actions/workflows/kwik-base-proj.yaml/dispatches
Authorization: token {{token}}
Accept: application/vnd.github+json
Content-Type: application/json
{
  "ref": "develop"
}

# 4 kwik5-template-project, build .ccx then release, this creates the release from develop branch!
POST https://api.github.com/repos/kwiksher/kwik5-project-template/actions/workflows/release.yaml/dispatches
Authorization: token {{token}}
Accept: application/vnd.github+json
Content-Type: application/json
{
  "ref": "develop"
}

# 5 local kwik5-plugin_build folder, ./build.sh to upload plugin.data.tgz
# 6 cd ../kwik5-project-template ./install_plugin.sh